AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Panorama application that counts people.
Parameters:
  bucketName:
    Description: Name of the project bucket
    Type: String
Resources:
  permissions:
    Type: AWS::IAM::Policy
    Properties: 
      Roles:
        - AWSPanoramaGreengrassGroupRole
      PolicyName: CloudWatch-permissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
            Condition:
              StringEquals:
                cloudwatch:namespace: PanoramaApp
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.main
      Runtime: python3.7
      CodeUri: code/.
      Description: Classification application.
      Timeout: 10
      AutoPublishAlias: DEVELOPMENT
      # Function's role
      Policies:
        - AWSLambdaBasicExecutionRole
  serviceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: bucket-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: !Sub arn:aws:s3:::${bucketName}
              - Effect: Allow
                Action: 's3:*'
                Resource: !Sub arn:aws:s3:::${bucketName}/*
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "sagemaker.amazonaws.com"
                ]
              }
            }
          ]
        }
Outputs:
  region:
    Description: The stack's region
    Value: !Ref AWS::Region
  roleArn: 
    Description: ARN of SageMaker service role
    Value: !GetAtt serviceRole.Arn
  bucketName:
    Description: Bucket name
    Value: !Ref bucketName